export enum TipoUsuarioEnum {
    ADMIN = 'ADMIN',
    ORQUESTRADOR = 'ORQUESTRADOR',
    BAGUA  = 'BAGUA',
    BSOLVENTE = 'BSOLVENTE',
    REPRESENTANTE = 'REPRESENTANTE',
    REPRE_ATENDENTE = 'REPRE_ATENDENTE',
}